#  Starter pipeline
# Start with a  minimal pipeline that you can customize to build and deploy your code.
# Add  steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# resources:
#  repositories:
#    - repository: R1
#      type: GitHub
#      endpoint: MyGithubConnection
#      name: jainamanjain/Repo1

jobs:
#  - deployment: deploymentJob1
#    displayName: somedeploy
#    pool:
#     name: default
#    environment: environment1
#    strategy:
#     runOnce:
#       deploy:
#         steps:
#          - checkout: self
#          - task: PublishBuildArtifacts@1
#            inputs:
#             PathtoPublish: 'artifact1.1'
#             ArtifactName: 'A1.1'
#             publishLocation: 'Container'
#          - task: PublishBuildArtifacts@1
#            inputs:
#             PathtoPublish: 'artifact1.2'
#             ArtifactName: 'A1.2'
#             publishLocation: 'Container'
#          - powershell: |
#             ls $(Build.ArtifactStagingDirectory)/
 - job: J1
   pool:
    name: default
   steps:
      - task: PublishBuildArtifacts@1
        inputs:
         PathtoPublish: 'artifact1.1'
         ArtifactName: 'A1.1'
         publishLocation: 'Container'
      - task: PublishBuildArtifacts@1
        inputs:
         PathtoPublish: 'artifact1.2'
         ArtifactName: 'A1.2'
         publishLocation: 'Container'
      - powershell: |
            ls $(Build.ArtifactStagingDirectory)/
 - job: J2
   pool:
    name: default
   steps:
      - task: PublishBuildArtifacts@1
        inputs:
         PathtoPublish: 'artifact2'
         ArtifactName: 'A2'
         publishLocation: 'Container'

 - job: J3
   pool:
    name: default
   dependsOn: J1
   steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          artifactName: 'A1.1'
          downloadPath: '$(System.ArtifactStagingDirectory)'
